2025-04-06 17:05:37.753 [info] (Client) Pylance async client (2025.4.1) started with python extension (2025.4.0)
2025-04-06 17:05:38.507 [info] [Info  - 5:05:38 PM] (38824) Server root directory: file:///home/shiy/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-06 17:05:38.507 [info] [Info  - 5:05:38 PM] (38824) Pylance language server 2025.4.1 (pyright version 1.1.398, commit 4f24eccc) starting
2025-04-06 17:05:38.511 [info] [Info  - 5:05:38 PM] (38824) Starting service instance "FastAPI-ToDoList" for workspace "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList"
2025-04-06 17:05:38.560 [info] [Info  - 5:05:38 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:05:38.561 [info] [Info  - 5:05:38 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:05:38.562 [info] [Info  - 5:05:38 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:05:38.563 [info] [Info  - 5:05:38 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:05:38.563 [info] [Info  - 5:05:38 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:05:38.564 [info] [Info  - 5:05:38 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:05:38.564 [info] [Info  - 5:05:38 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:05:38.564 [info] [Info  - 5:05:38 PM] (38824) Auto-excluding **/.*
2025-04-06 17:05:38.564 [info] [Error - 5:05:38 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:05:38.586 [info] [Info  - 5:05:38 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:05:39.866 [info] [Info  - 5:05:39 PM] (38824) Found 3 source files
2025-04-06 17:05:39.914 [info] [Info  - 5:05:39 PM] (38824) BG: Priority queue background worker(2) root directory: file:///home/shiy/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-06 17:05:39.914 [info] [Info  - 5:05:39 PM] (38824) BG: Priority queue background worker(2) started
2025-04-06 17:05:39.915 [info] [Info  - 5:05:39 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:05:39.915 [info] [Info  - 5:05:39 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:05:39.916 [info] [Info  - 5:05:39 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:05:39.916 [info] [Info  - 5:05:39 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:05:39.916 [info] [Info  - 5:05:39 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:05:39.916 [info] [Info  - 5:05:39 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:05:39.916 [info] [Info  - 5:05:39 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:05:39.916 [info] [Info  - 5:05:39 PM] (38824) Auto-excluding **/.*
2025-04-06 17:05:39.916 [info] [Error - 5:05:39 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:05:39.936 [info] [Info  - 5:05:39 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:05:39.974 [info] [Info  - 5:05:39 PM] (38824) Found 3 source files
2025-04-06 17:07:00.371 [info] [Info  - 5:07:00 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:07:00.371 [info] [Info  - 5:07:00 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) Auto-excluding **/.*
2025-04-06 17:07:00.372 [info] [Error - 5:07:00 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:07:00.372 [info] [Info  - 5:07:00 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:07:00.392 [info] [Info  - 5:07:00 PM] (38824) Found 3 source files
2025-04-06 17:07:43.569 [info] [Info  - 5:07:43 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:07:43.569 [info] [Info  - 5:07:43 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:07:43.569 [info] [Info  - 5:07:43 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:07:43.570 [info] [Info  - 5:07:43 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:07:43.570 [info] [Info  - 5:07:43 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:07:43.570 [info] [Info  - 5:07:43 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:07:43.570 [info] [Info  - 5:07:43 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:07:43.570 [info] [Info  - 5:07:43 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:07:43.570 [info] [Info  - 5:07:43 PM] (38824) Auto-excluding **/.*
2025-04-06 17:07:43.570 [info] [Error - 5:07:43 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:07:43.570 [info] [Info  - 5:07:43 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:07:43.589 [info] [Info  - 5:07:43 PM] (38824) Found 3 source files
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Auto-excluding **/.*
2025-04-06 17:08:20.837 [info] [Error - 5:08:20 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:08:20.837 [info] [Info  - 5:08:20 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:08:20.854 [info] [Info  - 5:08:20 PM] (38824) Found 3 source files
2025-04-06 17:08:38.285 [info] [Info  - 5:08:38 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Auto-excluding **/.*
2025-04-06 17:08:38.286 [info] [Error - 5:08:38 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:08:38.286 [info] [Info  - 5:08:38 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:08:38.302 [info] [Info  - 5:08:38 PM] (38824) Found 3 source files
2025-04-06 17:13:45.771 [info] [Info  - 5:13:45 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:13:45.771 [info] [Info  - 5:13:45 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) Auto-excluding **/.*
2025-04-06 17:13:45.772 [info] [Error - 5:13:45 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:13:45.772 [info] [Info  - 5:13:45 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:13:45.789 [info] [Info  - 5:13:45 PM] (38824) Found 3 source files
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:16:00.417 [info] [Info  - 5:16:00 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:16:00.418 [info] [Info  - 5:16:00 PM] (38824) Auto-excluding **/.*
2025-04-06 17:16:00.418 [info] [Error - 5:16:00 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:16:00.418 [info] [Info  - 5:16:00 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:16:00.432 [info] [Info  - 5:16:00 PM] (38824) Found 3 source files
2025-04-06 17:16:07.236 [info] [Info  - 5:16:07 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:07.236 [info] [Info  - 5:16:07 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:07.236 [info] [Info  - 5:16:07 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:16:07.236 [info] [Info  - 5:16:07 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:16:07.236 [info] [Info  - 5:16:07 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:16:07.237 [info] [Info  - 5:16:07 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:16:07.237 [info] [Info  - 5:16:07 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:16:07.237 [info] [Info  - 5:16:07 PM] (38824) Auto-excluding **/.*
2025-04-06 17:16:07.237 [info] [Error - 5:16:07 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:16:07.237 [info] [Info  - 5:16:07 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:16:07.251 [info] [Info  - 5:16:07 PM] (38824) Found 3 source files
2025-04-06 17:16:34.796 [info] [Info  - 5:16:34 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:34.796 [info] [Info  - 5:16:34 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:34.796 [info] [Info  - 5:16:34 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:16:34.796 [info] [Info  - 5:16:34 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:16:34.796 [info] [Info  - 5:16:34 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:16:34.796 [info] [Info  - 5:16:34 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:16:34.797 [info] [Info  - 5:16:34 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:16:34.797 [info] [Info  - 5:16:34 PM] (38824) Auto-excluding **/.*
2025-04-06 17:16:34.797 [info] [Error - 5:16:34 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:16:34.797 [info] [Info  - 5:16:34 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:16:34.812 [info] [Info  - 5:16:34 PM] (38824) Found 3 source files
2025-04-06 17:16:43.779 [info] [Info  - 5:16:43 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Auto-excluding **/.*
2025-04-06 17:16:43.780 [info] [Error - 5:16:43 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:16:43.780 [info] [Info  - 5:16:43 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:16:43.797 [info] [Info  - 5:16:43 PM] (38824) Found 3 source files
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Auto-excluding **/.*
2025-04-06 17:18:37.781 [info] [Error - 5:18:37 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:18:37.781 [info] [Info  - 5:18:37 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:18:37.797 [info] [Info  - 5:18:37 PM] (38824) Found 3 source files
2025-04-06 17:18:42.208 [info] [Info  - 5:18:42 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Pyproject file "/home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml" has no "[tool.pyright]" section.
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Auto-excluding **/.*
2025-04-06 17:18:42.209 [info] [Error - 5:18:42 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:18:42.209 [info] [Info  - 5:18:42 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:18:42.227 [info] [Info  - 5:18:42 PM] (38824) Found 3 source files
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Reloading configuration file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Loading pyproject.toml file at /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/pyproject.toml
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Setting environmentName for service "FastAPI-ToDoList": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Setting pythonPath for service "FastAPI-ToDoList": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) No include entries specified; assuming /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Auto-excluding **/.*
2025-04-06 17:18:45.964 [info] [Error - 5:18:45 PM] (38824) venvPath /home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList/.venv is not a valid directory.
2025-04-06 17:18:45.964 [info] [Info  - 5:18:45 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:18:45.981 [info] [Info  - 5:18:45 PM] (38824) Found 3 source files
2025-04-06 17:19:43.336 [info] [Info  - 5:19:43 PM] (38824) BG: Indexer background runner(3) root directory: file:///home/shiy/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist (refresh)
2025-04-06 17:19:43.336 [info] [Info  - 5:19:43 PM] (38824) BG: Indexing(3) started
2025-04-06 17:19:43.338 [info] [Info  - 5:19:43 PM] (38824) Starting service instance "<default>" for workspace ""
2025-04-06 17:19:43.384 [info] [Info  - 5:19:43 PM] (38824) Setting environmentName for service "<default>": "3.12.3 (fastapi-todolist-R83S90s3-py3.12 venv)"
2025-04-06 17:19:43.385 [info] [Info  - 5:19:43 PM] (38824) Setting pythonPath for service "<default>": "/home/shiy/.cache/pypoetry/virtualenvs/fastapi-todolist-R83S90s3-py3.12/bin/python"
2025-04-06 17:19:43.385 [info] [Info  - 5:19:43 PM] (38824) No include entries specified; assuming /<default workspace root>
2025-04-06 17:19:43.385 [info] [Info  - 5:19:43 PM] (38824) Auto-excluding **/node_modules
2025-04-06 17:19:43.385 [info] [Info  - 5:19:43 PM] (38824) Auto-excluding **/__pycache__
2025-04-06 17:19:43.385 [info] [Info  - 5:19:43 PM] (38824) Auto-excluding **/.*
2025-04-06 17:19:43.412 [info] [Info  - 5:19:43 PM] (38824) Assuming Python version 3.12.3.final.0
2025-04-06 17:19:43.465 [info] [Error - 5:19:43 PM] (38824) File or directory "/<default workspace root>" does not exist.
2025-04-06 17:19:43.465 [info] [Info  - 5:19:43 PM] (38824) No source files found.
2025-04-06 17:19:43.959 [info] [Info  - 5:19:43 PM] (38824) BG: Priority queue background worker(5) root directory: file:///home/shiy/.vscode/extensions/ms-python.vscode-pylance-2025.4.1/dist
2025-04-06 17:19:43.960 [info] [Info  - 5:19:43 PM] (38824) BG: Priority queue background worker(5) started
2025-04-06 17:19:45.021 [info] [Info  - 5:19:45 PM] (38824) BG: [IDX(3)] Long operation: scan packages file:///home/shiy/Desktop/Projects/portifolio/FastAPI-template/FastAPI-ToDoList (2190ms)
2025-04-06 17:19:45.021 [info] [Info  - 5:19:45 PM] (38824) BG: scanned(3) 75 files over 1 exec env
2025-04-06 17:19:45.536 [info] [Info  - 5:19:45 PM] (38824) BG: indexed(3) 75 files over 1 exec env
2025-04-06 17:19:45.556 [info] [Info  - 5:19:45 PM] (38824) BG: Indexing finished(3).
