2025-04-05 17:13:10.473 [info] Experiment 'pythonRecommendTensorboardExt' is active
2025-04-05 17:13:10.473 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2025-04-05 17:13:10.503 [info] Starting Environment refresh
2025-04-05 17:13:10.503 [info] Searching for interpreters in posix paths locator
2025-04-05 17:13:10.507 [info] Searching for pyenv environments
2025-04-05 17:13:10.507 [info] Searching for conda environments
2025-04-05 17:13:10.508 [info] Searching for global virtual environments
2025-04-05 17:13:10.508 [info] Searching for custom virtual environments
2025-04-05 17:13:10.518 [info] Finished searching for pyenv environments: 14 milliseconds
2025-04-05 17:13:10.518 [info] Finished searching for custom virtual envs: 14 milliseconds
2025-04-05 17:13:10.525 [info] > conda info --json
2025-04-05 17:13:10.528 [info] Finished searching for global virtual envs: 24 milliseconds
2025-04-05 17:13:10.532 [info] Found: /bin/python3 --> /bin/python3.12
2025-04-05 17:13:10.532 [info] Found: /bin/python3.12 --> /bin/python3.12
2025-04-05 17:13:10.545 [info] Found: /usr/bin/python3 --> /usr/bin/python3.12
2025-04-05 17:13:10.545 [info] Found: /usr/bin/python3.12 --> /usr/bin/python3.12
2025-04-05 17:13:10.562 [info] Finished searching for interpreters in posix paths locator: 53 milliseconds
2025-04-05 17:13:10.563 [info] > /bin/python3 -I ~/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/interpreterInfo.py
2025-04-05 17:13:10.572 [info] > /usr/bin/python3 -I ~/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/interpreterInfo.py
2025-04-05 17:13:10.572 [info] Environments refresh paths discovered (event): 70 milliseconds
2025-04-05 17:13:10.572 [info] Environments refresh paths discovered: 70 milliseconds
2025-04-05 17:13:10.597 [info] Environments refresh finished (event): 95 milliseconds
2025-04-05 17:13:10.601 [info] Environment refresh took 100 milliseconds
2025-04-05 17:13:10.605 [info] Python interpreter path: /bin/python3
2025-04-05 17:13:10.926 [info] Shell integration status changed, can confirm it's working.
2025-04-05 17:13:12.215 [info] Starting Pylance language server.
2025-04-05 17:14:41.985 [info] Searching for custom virtual environments
2025-04-05 17:14:41.987 [info] Active interpreter [global]:  /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python
2025-04-05 17:14:41.987 [info] Finished searching for custom virtual envs: 2 milliseconds
2025-04-05 17:14:41.987 [info] Environments refresh finished (event): 9 milliseconds
2025-04-05 17:14:41.987 [info] Environments refresh paths discovered: 9 milliseconds
2025-04-05 17:14:41.988 [warning] Failed to check if /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python is an executable [Error: ENOENT: no such file or directory, lstat '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'
}
2025-04-05 17:14:41.988 [warning] Failed to check if /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python is an executable [Error: ENOENT: no such file or directory, lstat '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'
}
2025-04-05 17:14:41.988 [warning] Failed to check if /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python is an executable [Error: ENOENT: no such file or directory, lstat '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'
}
2025-04-05 17:14:41.988 [warning] Failed to check if /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python is an executable [Error: ENOENT: no such file or directory, lstat '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python'
}
2025-04-05 17:14:41.996 [warning] Identifier for virt-virtualenv failed to identify /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python [Error: ENOENT: no such file or directory, scandir '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'
}
2025-04-05 17:14:41.996 [warning] Identifier for virt-virtualenv failed to identify /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python [Error: ENOENT: no such file or directory, scandir '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'
}
2025-04-05 17:14:41.996 [warning] Identifier for virt-virtualenv failed to identify /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python [Error: ENOENT: no such file or directory, scandir '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'
}
2025-04-05 17:14:41.996 [warning] Identifier for virt-virtualenv failed to identify /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python [Error: ENOENT: no such file or directory, scandir '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin'
}
2025-04-05 17:14:42.017 [info] > ~/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python -I ~/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/interpreterInfo.py
2025-04-05 17:14:42.019 [error] Error: Command failed: /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python -I /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/get_output_via_markers.py /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python: not found

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:423:12)
    at ChildProcess.emit (node:events:530:35)
    at maybeClose (node:internal/child_process:1104:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:518:28)
    at Pipe.<anonymous> (node:net:343:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: '/home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/out/client/.venv/bin/python -I /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/get_output_via_markers.py /home/shiy/.vscode/extensions/ms-python.python-2025.4.0-linux-x64/python_files/interpreterInfo.py'
}
